[project]
name = "agent-summarizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=0.3.78",
    "langgraph>=0.6.8",
    "notebook>=7.4.7",
]
